service: mod-success-2
useDotenv: true
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  region: ${self:custom.region}
  stackName: ${self:service}-${sls:stage}
  timeout: 29
  lambdaHashingVersion: 20201221

  environment:
    NODE_OPTIONS: --enable-source-maps
    SECRET_MANAGER_PREFIX: ${env:SECRET_MANAGER_PREFIX, '${self:service}/${sls:stage}'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - !Sub 'arn:aws:secretsmanager:eu-west-1:${AWS::AccountId}:secret:*'

  logRetentionInDays: 180
  tracing:
    lambda: true

functions:
  submitGroundLeaseRequest:
    handler: src/handlers/test.handler
    events:
      - http:
          path: /test
          method: POST
          cors: true
    vpc:
      securityGroupIds:
        - !Ref AWSServicesSecurityGroup

resources:
  Resources:
    AWSServicesSecurityGroup: ${file(incl-sls.yml):Resources.AWSServicesSecurityGroup}

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-prune-plugin

custom:
  region: ${opt:region, 'eu-west-1'}

  esbuild:
    minify: false
    bundle: true
    sourcemap: true
    watch:
      pattern: ['src/**/*.ts', '../../connectors/**/*.ts', '../../utils/**/*.ts']
      ignore: ['.serverless/**/*', '.build', '.esbuild']
    packager: yarn

  prune:
    automatic: true
    number: 3
